name: HiFiNi 自动签到
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '30 18 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v3
            - name: Set go
              uses: actions/setup-go@v3
              with:
                go-version: '^1.14'
            - name: HIFINI 自动签到
              env:
                COOKIE: ${{ bbs_sid=u1lgntrcernrbrm0b9o38j739o; bbs_token=PNy6j4APQUWKmfsWkZu8PdvdRXc0SkWPt3iNmBAZKBFz3irs1VCFHje9kC_2BEYR4F2VCVJyyXAC2z12AG3OkNWbsS8Q0OuSLz }}
                DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
              run: go run main.go
